USE [master]
GO

/****** Object:  Database [MIM.SyncReplica]    Script Date: 7/12/2021 4:41:47 PM ******/
IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = N'MIM.SyncReplica')
BEGIN
CREATE DATABASE [MIM.SyncReplica]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MIM.SyncReplica', FILENAME = N'D:\Data\MIM.SyncReplica.mdf' , SIZE = 15360KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'MIM.SyncReplica_log', FILENAME = N'E:\Logs\MIM.SyncReplica_log.ldf' , SIZE = 164864KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
END

GO

ALTER DATABASE [MIM.SyncReplica] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MIM.SyncReplica].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MIM.SyncReplica] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MIM.SyncReplica] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MIM.SyncReplica] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MIM.SyncReplica] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MIM.SyncReplica] SET ARITHABORT OFF 
GO

ALTER DATABASE [MIM.SyncReplica] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [MIM.SyncReplica] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [MIM.SyncReplica] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MIM.SyncReplica] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MIM.SyncReplica] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MIM.SyncReplica] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MIM.SyncReplica] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MIM.SyncReplica] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MIM.SyncReplica] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MIM.SyncReplica] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MIM.SyncReplica] SET  DISABLE_BROKER 
GO

ALTER DATABASE [MIM.SyncReplica] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MIM.SyncReplica] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MIM.SyncReplica] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MIM.SyncReplica] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MIM.SyncReplica] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MIM.SyncReplica] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [MIM.SyncReplica] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MIM.SyncReplica] SET RECOVERY FULL 
GO

ALTER DATABASE [MIM.SyncReplica] SET  MULTI_USER 
GO

ALTER DATABASE [MIM.SyncReplica] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MIM.SyncReplica] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MIM.SyncReplica] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [MIM.SyncReplica] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [MIM.SyncReplica] SET  READ_WRITE 
GO

USE [MIM.SyncReplica]
GO

/****** Object:  User [DBB\svcSSIS]    Script Date: 7/12/2021 4:42:01 PM ******/
IF NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = N'DBB\svcSSIS')
CREATE USER [DBB\svcSSIS] FOR LOGIN [DBB\svcSSIS] WITH DEFAULT_SCHEMA=[dbo]
GO


