//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mms_Metaverse.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>DBB</string>
  <string>DBB Contacts</string>
  <string>DerivedADS.group Updater</string>
  <string>DerivedADS.nestedGroup Updater</string>
  <string>NASS</string>
  <string>CAPS Payroll</string>
  <string>Legacy Exchange - migrated mailboxes</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ActiveMAs {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ActiveMAs"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dbb.local")]
        public string UPN {
            get {
                return ((string)(this["UPN"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>CN=Normal Mailboxes (A-G),CN=Storage Group 1,CN=InformationStore,CN=OCCCP-EX001,CN=Servers,CN=Curia,CN=Administrative Groups,CN=Diocese Of Broken Bay,CN=Microsoft Exchange,CN=Services,CN=Configuration,DC=dbb,DC=local</string>
  <string>CN=Normal Mailboxes (H-O),CN=Storage Group 1,CN=InformationStore,CN=OCCCP-EX001,CN=Servers,CN=Curia,CN=Administrative Groups,CN=Diocese Of Broken Bay,CN=Microsoft Exchange,CN=Services,CN=Configuration,DC=dbb,DC=local</string>
  <string>CN=Normal Mailboxes (P-Z),CN=Storage Group 1,CN=InformationStore,CN=OCCCP-EX001,CN=Servers,CN=Curia,CN=Administrative Groups,CN=Diocese Of Broken Bay,CN=Microsoft Exchange,CN=Services,CN=Configuration,DC=dbb,DC=local</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ExchangeMBXDNs {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ExchangeMBXDNs"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("01011900")]
        public string defaultUserPassword {
            get {
                return ((string)(this["defaultUserPassword"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int maxSAMAccountNameLength {
            get {
                return ((int)(this["maxSAMAccountNameLength"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int maxSAMAccountNameRetries {
            get {
                return ((int)(this["maxSAMAccountNameRetries"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Office of the Bishop</string>
  <string>Centacare</string>
  <string>Parishes</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection OrganisationOUs {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["OrganisationOUs"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OU=Disabled User Accounts,OU=Global Accounts,DC=dbb,DC=local")]
        public string DisabledUserAccountsOU {
            get {
                return ((string)(this["DisabledUserAccountsOU"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("X400:c=US;a= ;p=Exchange5.5;o=NT4DOMAIN;s")]
        public string ORAddress {
            get {
                return ((string)(this["ORAddress"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OU=Security,OU=Groups,DC=dbb,DC=local")]
        public string GroupsOU {
            get {
                return ((string)(this["GroupsOU"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OU=Staff,OU=Users,OU=Diocese,DC=dbb,DC=local")]
        public string StaffOU {
            get {
                return ((string)(this["StaffOU"]));
            }
        }
    }
}
