#-------------------------------------------------------------------------------
# Get-SAS2IDMMissingAndMismatching.ps1
#
# Identify missing or mismatching data between between each of SAS (44), SAS2IDM (1) and MIM Sync (1) databases
#
# Author: Bob Bradley - bob.bradley@unifysolutions.net
#         https://unifysolutions.net/identity/
# Change History
#         1/03/2022 - initial version
#
# Detailed Requirements
# * Identify missing or mismatching data between between each of SAS (44), SAS2IDM (1) and MIM Sync (1) databases
# * Report to be run either scheduled or on demand
# * Summary data to be sent via email as both HTML and CSV attachment
#-------------------------------------------------------------------------------
param(
    [string]$mimServer = "D-OCCCP-IM301",
    [string]$sasServer = "OCCCP-DB222",
    [string]$schoolCode = "%",
    [string]$logfile = "D:\Logs\Get-SAS2IDMMissingAndMismatching.log",
    [string]$cssfile = "D:\Scripts\Report.css",
    [string]$outputfile = "D:\Logs\SAS2IDMMissingAndMismatching.csv",
    [string]$company = "CSODBB",
    [string]$subject = "SAS to MIM Missing or Mismatching Students report",
    [string]$description = "Detail report to identify [{0}] missing or mismatching data between between each of SAS (44), SAS2IDM (1) and MIM Sync (1) databases",
    [string]$fromaddress = "MIMPROD@dbb.org.au", 
    [string[]]$toaddress = @("sat.support@dbb.org.au"),
    [string]$ccaddress = "csodbbsupport@unifysolutions.net",
    [string]$smtpserver = "localhost", #smtp.dbb.local",
    [switch]$debug,
    [switch]$help
)

# quit on errors
$ErrorActionPreference="Stop"

# show help
if ($help) {
    @"
NAME
    Get-SAS2IDMMissingAndMismatching

SYNOPSIS
    Detail report to identify missing or mismatching data between between each of SAS (44), SAS2IDM (1) and MIM Sync (1) databases.
    
SYNTAX:
    Get-SAS2IDMMissingAndMismatching [[-mimServer] <string>] [[-sasServer] <string>] [[-logfile] <string>] [[-outputfile] <string>] [-help] [-debug]

PARAMETERS:
    -mimServer <string> 
        The MIM Sync host server. The default value is '.' (localhost SQL in TEST, OCCCP-DB222 in PROD)
    
    -sasServer <string>
        The SAS and SAS2IDM host server. The default value is 'OCCCP-DB222'

    -schoolCode <string>
        The school code. The default value is '%' (wildcard syntax for ALL schools)

    -logfile <string>
        The log file for the last execution record this script. The default value is "D:\Logs\Get-SAS2IDMMissingAndMismatching.log".

    -cssfile <string>
        The CSS file required by the script for formatting HTML notifications. The default value is "D:\Scripts\Report.css".

    -outputfile <string>
        The CSV file generated by the script. The default value is "D:\Logs\SAS2IDMMissingAndMismatching.csv".

    -company <string>
        The company for whom this report is generated

    -subject <string>
        The report subject

    -description <string>
        The detailed report description

    -fromaddress <string>
        The notification sender email address

    -toaddress []<string>
        The notification recipient email address(es)

    -ccaddress <string>
        The notification CC recipient email address

    -smtpserver <string>
        The SMTP address (if null or empty string, no email will be sent)

    -debug <switch>
        Enable debug messages.

    -help <switch>
        Display this help message and exit.
        
"@
    exit
}

#------------------------------------------------------------------------------------------------------
# Send Email as an attachment
# Based on https://mdaslam.wordpress.com/2015/12/30/powershell-zip-files-and-send-email-with-attachment/
#------------------------------------------------------------------------------------------------------
Function Create-Zip
{
    Param(
        [String]$ZipFileName)
    End
    {
        [string]$tempPath = "$logFilePath\temp"
        New-Item -Force -ItemType directory -Path $tempPath | Out-Null
        Get-ChildItem "$($logFile.Replace($logFileExtension,".csv"))” | ForEach-Object {Copy-Item $_ $tempPath} | Out-Null

        if (Test-Path -path $("$ZipFileName")) 
        { 
            Remove-Item -Force $("$ZipFileName") | Out-Null
        }

        Add-Type -AssemblyName "System.IO.Compression.FileSystem" 
        [System.IO.Compression.ZipFile]::CreateFromDirectory($tempPath, $("$ZipFileName")) | Out-Null

        Remove-Item -Force -Recurse $tempPath | Out-Null
        Return $("$ZipFileName")
    }
}

#------------------------------------------------------------------------------------------------------
# Execute a SQL statement
#------------------------------------------------------------------------------------------------------
function ExecuteSQL 
{
    Param(
        [String]$sql="",
        [String]$connStr="",
        [Int]$cmdTimeout=120,
        [Bool]$dbg=$false)
    End
    {
        if ($sql.Length.Equals(0)) {
            Throw "Mandatory parameter sql not supplied!"
        }
        if ($connStr.Length.Equals(0)) {
            Throw "Mandatory parameter connStr not supplied!"
        }
        $sqlConnection = new-object System.Data.SqlClient.SqlConnection
        $sqlConnection.ConnectionString = $connStr
        if($dbg -eq $true) {Write-Output "Opening SQL Connection => [$($sqlCommand.ConnectionString)] ..." | Out-File -FilePath $logfile -Append}
        $sqlConnection.Open()
        [System.Data.SqlClient.SqlCommand]$sqlCommand = new-object System.Data.SqlClient.SqlCommand
        $sqlCommand.CommandTimeout = $cmdTimeout
        $sqlCommand.Connection = $sqlConnection
        $sqlCommand.CommandText= $sql
        if($dbg -eq $true) {Write-Output "Executing SQL: [$($sqlCommand.CommandText)]" | Out-File -FilePath $logfile -Append}
        [System.Data.DataTable]$dataTable = New-Object System.Data.DataTable
        [System.Data.SqlClient.SqlDataAdapter]$sqlAdapter = New-Object System.Data.SqlClient.SqlDataAdapter
        $sqlAdapter.SelectCommand = $sqlCommand
        $sqlAdapter.Fill($dataTable)
        $sqlConnection.Close() 
        if($Err){throw $Err}
        return $dataTable #$result
    }
 }

# Initialize hash table for result consolidation
$csvHT = @{}

# initiate logging
if ($debug) {
    Write-Output "$(Get-Date): Generating Report ..."
} else {
    Write-Output "$(Get-Date): Generating Report ..." | Out-File -FilePath $logfile
}

# -- Step #1: Get Missing USIN data from 44 schools
Write-Output "[$(Get-Date)] Getting Missing USIN data ..." | Out-File -FilePath $logfile -Append
$db = "SAS2IDM_SAS2IDM_LIVE"
$conn = "server=$sasServer;database=$db;Integrated Security=SSPI"
$sql = @"
exec [dbo].[procSAS2IDM_GetMissingUSIN_AllSchools]
"@

$sqlQueryResult = $null
try {
    $sqlQueryResult = @(ExecuteSQL -connStr $conn -sql $sql -cmdTimeout 600)
} catch {
    $err[0]
}

if ($sqlQueryResult) {
    $sqlQueryResult.Where({$_.NewUSIN -and ($_.SchoolCode -like $schoolCode.Replace('%','*'))}) | % {
        [string]$id = ("{0}:{1}" -f $_.NewUSIN, $_.SchoolCode)
        [string]$USIN = $_.NewUSIN
        if ($USIN -and $csvHT.ContainsKey($id)) {
            $csvHT.($id).Add("IsMissingUSIN",$true)
            $csvHT.($id).Add("IsMissingCeIder",$false)
            $csvHT.($id).Add("IsMissingEmailPrefix",$false)
            $csvHT.($id).Add("IsMissingCandidateNumber",$false)
            $csvHT.($id).Add("IsMissingLockerNumber",$false)
            $csvHT.($id).Add("IsMissingEmail",$false)
            $csvHT.($id).Add("IsMismatchingCeIder",$false)
            $csvHT.($id).Add("IsMismatchingLockerNumber",$false)
            $csvHT.($id).Add("IsMismatchingEmail",$false)
        } else {
            if ($USIN) {
                $csvHT.Add($id, @{})
                $csvHT.($id).Add("USIN",$USIN)
                $csvHT.($id).Add("MIM.SchoolID",$_.'MIM.SchoolID')
                $csvHT.($id).Add("MIM.FormerUSIN",$_.'MIM.FormerUSIN')
                $csvHT.($id).Add("MIM.CeIder",$_.'MIM.CeIder')
                $csvHT.($id).Add("MIM.EmailPrefix",$_.'MIM.EmailPrefix')
                $csvHT.($id).Add("MIM.DOB",$_.'MIM.DOB')
                $csvHT.($id).Add("StudentID",$_.StudentID)
                $csvHT.($id).Add("SchoolID",$_.SchoolID)
                $csvHT.($id).Add("SchoolCode",$_.SchoolCode)
                $csvHT.($id).Add("SchoolNumber",$_.SchoolNumber)
                $csvHT.($id).Add("CandidateNumber",$_.CandidateNumber)
                $csvHT.($id).Add("LockerNumber",$_.LockerNumber)
                $csvHT.($id).Add("Email",$_.Email)
                $csvHT.($id).Add("Code",$_.Code)
                $csvHT.($id).Add("DOB",$_.DOB)
                $csvHT.($id).Add("Year",$_.Year)
                $csvHT.($id).Add("FirstName",$_.FirstName)
                $csvHT.($id).Add("LastName",$_.LastName)
                $csvHT.($id).Add("UpdatedWhen",$_.UpdatedWhen)
                $csvHT.($id).Add("IsMissingUSIN",$true)
                $csvHT.($id).Add("IsMissingCeIder",$false)
                $csvHT.($id).Add("IsMissingEmailPrefix",$false)
                $csvHT.($id).Add("IsMissingCandidateNumber",$false)
                $csvHT.($id).Add("IsMissingLockerNumber",$false)
                $csvHT.($id).Add("IsMissingEmail",$false)
                $csvHT.($id).Add("IsMismatchingCeIder",$false)
                $csvHT.($id).Add("IsMismatchingLockerNumber",$false)
                $csvHT.($id).Add("IsMismatchingEmail",$false)
            }
        }
    }
}

# -- Step #2: Get Missing Ceider/Other data from 44 schools
Write-Output "[$(Get-Date)] Getting Missing CeIder/other data ..." | Out-File -FilePath $logfile -Append
$sql = @"
exec [dbo].[procSAS2IDM_GetMissingCeIder_AllSchools]
"@

$sqlQueryResult = $null
try {
    $sqlQueryResult = @(ExecuteSQL -connStr $conn -sql $sql -cmdTimeout 600)
} catch {
    $err[0]
}

if ($sqlQueryResult) {
    $sqlQueryResult.Where({$_.USIN -and ($_.SchoolCode -like $schoolCode.Replace('%','*'))}) | % {
        [string]$id = ("{0}:{1}" -f $_.USIN, $_.SchoolCode)
        [string]$USIN = $_.USIN
        if ($USIN -and $csvHT.ContainsKey($id)) {
            $csvHT.($id).Add("IsMissingUSIN",$false)
            $csvHT.($id).Add("IsMissingCeIder",[string]::IsNullOrEmpty($_.'MIM.CeIder'))
            $csvHT.($id).Add("IsMissingEmailPrefix",[string]::IsNullOrEmpty($_.'MIM.EmailPrefix'))
            $csvHT.($id).Add("IsMissingCandidateNumber",[string]::IsNullOrEmpty($_.CandidateNumber))
            $csvHT.($id).Add("IsMissingLockerNumber",[string]::IsNullOrEmpty($_.LockerNumber))
            $csvHT.($id).Add("IsMissingEmail",[string]::IsNullOrEmpty($_.Email))
            $csvHT.($id).Add("IsMismatchingCeIder",($_.'MIM.CeIder' -ine $_.CandidateNumber))
            $csvHT.($id).Add("IsMismatchingLockerNumber",(($_.'MIM.Email' -ireplace '@dbbstu.catholic.edu.au','') -ine $_.LockerNumber))
            $csvHT.($id).Add("IsMismatchingEmail",($_.'MIM.Email' -ine $_.Email))
        } else {
            if ($USIN) {
                $csvHT.Add($id, @{})
                $csvHT.($id).Add("USIN",$USIN)
                $csvHT.($id).Add("MIM.SchoolID",$_.'MIM.SchoolID')
                $csvHT.($id).Add("MIM.FormerUSIN",$_.'MIM.FormerUSIN')
                $csvHT.($id).Add("MIM.CeIder",$_.'MIM.CeIder')
                $csvHT.($id).Add("MIM.EmailPrefix",$_.'MIM.EmailPrefix')
                $csvHT.($id).Add("MIM.DOB",$_.'MIM.DOB')
                $csvHT.($id).Add("StudentID",$_.StudentID)
                $csvHT.($id).Add("SchoolID",$_.SchoolID)
                $csvHT.($id).Add("SchoolCode",$_.SchoolCode)
                $csvHT.($id).Add("SchoolNumber",$_.SchoolNumber)
                $csvHT.($id).Add("CandidateNumber",$_.CandidateNumber)
                $csvHT.($id).Add("LockerNumber",$_.LockerNumber)
                $csvHT.($id).Add("Email",$_.Email)
                $csvHT.($id).Add("Code",$_.Code)
                $csvHT.($id).Add("DOB",$_.DOB)
                $csvHT.($id).Add("Year",$_.Year)
                $csvHT.($id).Add("FirstName",$_.FirstName)
                $csvHT.($id).Add("LastName",$_.LastName)
                $csvHT.($id).Add("UpdatedWhen",$_.UpdatedWhen)
                $csvHT.($id).Add("IsMissingUSIN",$false)
                $csvHT.($id).Add("IsMissingCeIder",[string]::IsNullOrEmpty($_.'MIM.CeIder'))
                $csvHT.($id).Add("IsMissingEmailPrefix",[string]::IsNullOrEmpty($_.'MIM.EmailPrefix'))
                $csvHT.($id).Add("IsMissingCandidateNumber",[string]::IsNullOrEmpty($_.CandidateNumber))
                $csvHT.($id).Add("IsMissingLockerNumber",[string]::IsNullOrEmpty($_.LockerNumber))
                $csvHT.($id).Add("IsMissingEmail",[string]::IsNullOrEmpty($_.Email))
                $csvHT.($id).Add("IsMismatchingCeIder",($_.'MIM.CeIder' -ine $_.CandidateNumber))
                $csvHT.($id).Add("IsMismatchingLockerNumber",(($_.'MIM.Email' -ireplace '@dbbstu.catholic.edu.au','') -ine $_.LockerNumber))
                $csvHT.($id).Add("IsMismatchingEmail",($_.'MIM.Email' -ine $_.Email))
            }
        }
    }
}

# -- Step #3: Get Mismatching Ceider/Other data from 44 schools
Write-Output "[$(Get-Date)] Getting Mismatching CeIder/other data ..." | Out-File -FilePath $logfile -Append
$sql = @"
exec [dbo].[procSAS2IDM_GetMismatchingCeIder_AllSchools]
"@

$sqlQueryResult = $null
try {
    $sqlQueryResult = @(ExecuteSQL -connStr $conn -sql $sql -cmdTimeout 600)
} catch {
    $err[0]
}

if ($sqlQueryResult) {
    $sqlQueryResult.Where({$_.USIN -and ($_.SchoolCode -like $schoolCode.Replace('%','*'))}) | % {
        [string]$id = ("{0}:{1}" -f $_.USIN, $_.SchoolCode)
        [string]$USIN = $_.USIN
        if ($USIN -and $csvHT.ContainsKey($id)) {
            $csvHT.($id).'IsMismatchingCeIder' = ($_.'MIM.CeIder' -ine $_.CandidateNumber)
            $csvHT.($id).'IsMismatchingLockerNumber' = (($_.'MIM.Email' -ireplace '@dbbstu.catholic.edu.au','') -ine $_.LockerNumber)
            $csvHT.($id).'IsMismatchingEmail' = ($_.'MIM.Email' -ine $_.Email)
        } else {
            if ($USIN) {
                $csvHT.Add($id, @{})
                $csvHT.($id).Add("USIN",$USIN)
                $csvHT.($id).Add("MIM.SchoolID",$_.'MIM.SchoolID')
                $csvHT.($id).Add("MIM.FormerUSIN",$_.'MIM.FormerUSIN')
                $csvHT.($id).Add("MIM.CeIder",$_.'MIM.CeIder')
                $csvHT.($id).Add("MIM.EmailPrefix",$_.'MIM.EmailPrefix')
                $csvHT.($id).Add("MIM.DOB",$_.'MIM.DOB')
                $csvHT.($id).Add("StudentID",$_.StudentID)
                $csvHT.($id).Add("SchoolID",$_.SchoolID)
                $csvHT.($id).Add("SchoolCode",$_.SchoolCode)
                $csvHT.($id).Add("SchoolNumber",$_.SchoolNumber)
                $csvHT.($id).Add("CandidateNumber",$_.CandidateNumber)
                $csvHT.($id).Add("LockerNumber",$_.LockerNumber)
                $csvHT.($id).Add("Email",$_.Email)
                $csvHT.($id).Add("Code",$_.Code)
                $csvHT.($id).Add("DOB",$_.DOB)
                $csvHT.($id).Add("Year",$_.Year)
                $csvHT.($id).Add("FirstName",$_.FirstName)
                $csvHT.($id).Add("LastName",$_.LastName)
                $csvHT.($id).Add("UpdatedWhen",$_.UpdatedWhen)
                $csvHT.($id).Add("IsMissingUSIN",$false)
                $csvHT.($id).Add("IsMissingCeIder",$false)
                $csvHT.($id).Add("IsMissingEmailPrefix",$false)
                $csvHT.($id).Add("IsMissingCandidateNumber",$false)
                $csvHT.($id).Add("IsMissingLockerNumber",$false)
                $csvHT.($id).Add("IsMissingEmail",$false)
                $csvHT.($id).Add("IsMismatchingCeIder",($_.'MIM.CeIder' -ine $_.CandidateNumber))
                $csvHT.($id).Add("IsMismatchingLockerNumber",(($_.'MIM.Email' -ireplace '@dbbstu.catholic.edu.au','') -ine $_.LockerNumber))
                $csvHT.($id).Add("IsMismatchingEmail",($_.'MIM.Email' -ine $_.Email))
            }
        }
    }
}

# -- Step $5: determine report type
$csvHT.Keys | % {
    if ($csvHT.($_).'IsMissingUSIN') { $csvHT.($_).Add("Report","Missing USINs") }
    elseif ($csvHT.($_).'IsMissingCeIder') { $csvHT.($_).Add("Report","Missing CeIders (MIM)") }
    elseif ($csvHT.($_).'IsMissingEmailPrefix') { $csvHT.($_).Add("Report","Missing Accounts (MIM)") }
    elseif ($csvHT.($_).'IsMissingCandidateNumber') { $csvHT.($_).Add("Report","Missing Candidates (SAS)") }
    elseif ($csvHT.($_).'IsMissingLockerNumber') { $csvHT.($_).Add("Report","Missing Lockers (SAS)") }
    elseif ($csvHT.($_).'IsMissingEmail') { $csvHT.($_).Add("Report","Missing Emails (SAS)") }
    elseif ($csvHT.($_).'IsMismatchingCeIder') { $csvHT.($_).Add("Report","Mismatching Ceiders (SAS/MIM)") }
    elseif ($csvHT.($_).'IsMismatchingLockerNumber') { $csvHT.($_).Add("Report","Mismatching Lockers (SAS/MIM)") }
    elseif ($csvHT.($_).'IsMismatchingEmail') { $csvHT.($_).Add("Report","Mismatching Emails (SAS/MIM)") }
}

# -- Step #4: Generate CSV Report
# Extend log file name with date/time component
[string]$logFileExtension = [System.IO.Path]::GetExtension($logFile)
[string]$logFileExt = [System.IO.Path]::Combine($logFilePath, $logFile.Replace($logFileExtension, "."+(get-date -Format "yyyy-MM-dd")+$logFileExtension))
[string]$logFilePath = [System.IO.Path]::GetDirectoryName($logfile)
[string]$outputfile = $logFile.Replace($logFileExtension,".csv")
if (Test-Path -path $outputfile) 
{ 
    Remove-Item -Force $outputfile | Out-Null
}

Write-Output "[$(Get-Date)] Writing CSV to $outputfile ..." | Out-File -FilePath $logfile -Append
[int]$csvCount = 0
$colHeader = @("Report","SchoolCode","USIN","SchoolNumber","MIM.CeIder","MIM.EmailPrefix","MIM.SchoolID","Code","CandidateNumber","MIM.DOB","FirstName","LastName","DOB","LockerNumber","MIM.FormerUSIN","StudentID","Email","UpdatedWhen","Year")
foreach($csvItem in $csvHT.Keys) {
    if ($csvItem.Length -gt 0) {
        if (($csvHT.($csvItem).USIN.Length -gt 0) -and (!$csvHT.($csvItem).InMIM -or !$csvHT.($csvItem).InSAS2IDM -or !$csvHT.($csvItem).InSAS)) {
            [PSCustomObject]$csvHT.($csvItem) | select $colHeader | Export-Csv $outputfile –NoTypeInformation -Append
            $csvCount++
        }
    }
}

if ((Test-Path -path $outputfile) -and ($smtpserver.Length -gt 0)) {
    [string]$archiveFileName = $outputfile -ireplace ".CSV",".ZIP"
    [string]$head = get-content $cssfile
    [string]$spacer = "<table><tr><td class='Spacer'/></tr></table>"
    [string]$reportData = [PSCustomObject]@{Company=$company;Date="$(Get-Date)";Server="$($env:COMPUTERNAME)";} | select * | ConvertTo-Html -Fragment -PreContent "<h3>$($description -f $csvCount)</h3>" | Out-String
    [string]$reportBody = Get-Content -Path $outputfile | ConvertFrom-Csv | Sort-object "Report" -Descending | ConvertTo-Html -Fragment -PreContent $spacer | Out-String
    [string]$body = ConvertTo-Html -Head $head -PostContent $reportBody -PreContent "<h1>$subject</h1>",$reportData
    $attachment = Create-Zip -ZipFileName $archiveFileName
    Send-MailMessage -SmtpServer $smtpserver -Body $body -BodyAsHtml -From $fromaddress -To $toaddress -Cc $ccaddress -Subject $subject -Attachments $attachment
    $attachment = $null
}
        
# finalise logging
if ($debug) {
    Write-Output "$(Get-Date): Report generated OK!"
} else {
    Write-Output "$(Get-Date): Report generated OK!" | Out-File -FilePath $logfile -Append
}
