USE [SAS2000_LIVE_SCCSI];
GO
:r C:\scripts\SAS2IDM.SSIS\Create-Role_db_SAS2IDM_SSIS.sql
GO
USE [SAS2000_LIVE_SHCPK];
GO
:r C:\scripts\SAS2IDM.SSIS\Create-Role_db_SAS2IDM_SSIS.sql
GO
USE [SAS2000_LIVE_SHFPL];
GO
:r C:\scripts\SAS2IDM.SSIS\Create-Role_db_SAS2IDM_SSIS.sql
GO
USE [SAS2000_LIVE_SMCCC];
GO
:r C:\scripts\SAS2IDM.SSIS\Create-Role_db_SAS2IDM_SSIS.sql
GO
USE [SAS2000_LIVE_SMCCW];
GO
:r C:\scripts\SAS2IDM.SSIS\Create-Role_db_SAS2IDM_SSIS.sql
GO
USE [SAS2000_LIVE_SMMCW];
GO
:r C:\scripts\SAS2IDM.SSIS\Create-Role_db_SAS2IDM_SSIS.sql
GO
USE [SAS2000_LIVE_SMRPA];
GO
:r C:\scripts\SAS2IDM.SSIS\Create-Role_db_SAS2IDM_SSIS.sql
GO
USE [SAS2000_LIVE_SOLDC];
GO
:r C:\scripts\SAS2IDM.SSIS\Create-Role_db_SAS2IDM_SSIS.sql
GO
USE [SAS2000_LIVE_SOLGF];
GO
:r C:\scripts\SAS2IDM.SSIS\Create-Role_db_SAS2IDM_SSIS.sql
GO
USE [SAS2000_LIVE_SOLHE];
GO
:r C:\scripts\SAS2IDM.SSIS\Create-Role_db_SAS2IDM_SSIS.sql
GO
USE [SAS2000_LIVE_SOLPW];
GO
:r C:\scripts\SAS2IDM.SSIS\Create-Role_db_SAS2IDM_SSIS.sql
GO
USE [SAS2000_LIVE_SOLRE];
GO
:r C:\scripts\SAS2IDM.SSIS\Create-Role_db_SAS2IDM_SSIS.sql
GO
USE [SAS2000_LIVE_SOLST];
GO
:r C:\scripts\SAS2IDM.SSIS\Create-Role_db_SAS2IDM_SSIS.sql
GO
USE [SAS2000_LIVE_SOLWA];
GO
:r C:\scripts\SAS2IDM.SSIS\Create-Role_db_SAS2IDM_SSIS.sql
GO
USE [SAS2000_LIVE_SOLWY];
GO
:r C:\scripts\SAS2IDM.SSIS\Create-Role_db_SAS2IDM_SSIS.sql
GO
USE [SAS2000_LIVE_SPCSW];
GO
:r C:\scripts\SAS2IDM.SSIS\Create-Role_db_SAS2IDM_SSIS.sql
GO
USE [SAS2000_LIVE_SSAPH];
GO
:r C:\scripts\SAS2IDM.SSIS\Create-Role_db_SAS2IDM_SSIS.sql
GO
USE [SAS2000_LIVE_SSBBH];
GO
:r C:\scripts\SAS2IDM.SSIS\Create-Role_db_SAS2IDM_SSIS.sql
GO
USE [SAS2000_LIVE_SSBCL];
GO
:r C:\scripts\SAS2IDM.SSIS\Create-Role_db_SAS2IDM_SSIS.sql
GO
USE [SAS2000_LIVE_SSBLM];
GO
:r C:\scripts\SAS2IDM.SSIS\Create-Role_db_SAS2IDM_SSIS.sql
GO
USE [SAS2000_LIVE_SSCPB];
GO
:r C:\scripts\SAS2IDM.SSIS\Create-Role_db_SAS2IDM_SSIS.sql
GO
USE [SAS2000_LIVE_SSCPW];
GO
:r C:\scripts\SAS2IDM.SSIS\Create-Role_db_SAS2IDM_SSIS.sql
GO
USE [SAS2000_LIVE_SSGPC];
GO
:r C:\scripts\SAS2IDM.SSIS\Create-Role_db_SAS2IDM_SSIS.sql
GO
USE [SAS2000_LIVE_SSHMV];
GO
:r C:\scripts\SAS2IDM.SSIS\Create-Role_db_SAS2IDM_SSIS.sql
GO
USE [SAS2000_LIVE_SSHPP];
GO
:r C:\scripts\SAS2IDM.SSIS\Create-Role_db_SAS2IDM_SSIS.sql
GO
USE [SAS2000_LIVE_SSJAN];
GO
:r C:\scripts\SAS2IDM.SSIS\Create-Role_db_SAS2IDM_SSIS.sql
GO
USE [SAS2000_LIVE_SSJBH];
GO
:r C:\scripts\SAS2IDM.SSIS\Create-Role_db_SAS2IDM_SSIS.sql
GO
USE [SAS2000_LIVE_SSJGE];
GO
:r C:\scripts\SAS2IDM.SSIS\Create-Role_db_SAS2IDM_SSIS.sql
GO
USE [SAS2000_LIVE_SSJPN];
GO
:r C:\scripts\SAS2IDM.SSIS\Create-Role_db_SAS2IDM_SSIS.sql
GO
USE [SAS2000_LIVE_SSJTU];
GO
:r C:\scripts\SAS2IDM.SSIS\Create-Role_db_SAS2IDM_SSIS.sql
GO
USE [SAS2000_LIVE_SSJWW];
GO
:r C:\scripts\SAS2IDM.SSIS\Create-Role_db_SAS2IDM_SSIS.sql
GO
USE [SAS2000_LIVE_SSKDW];
GO
:r C:\scripts\SAS2IDM.SSIS\Create-Role_db_SAS2IDM_SSIS.sql
GO
USE [SAS2000_LIVE_SSKMV];
GO
:r C:\scripts\SAS2IDM.SSIS\Create-Role_db_SAS2IDM_SSIS.sql
GO
USE [SAS2000_LIVE_SSLCW];
GO
:r C:\scripts\SAS2IDM.SSIS\Create-Role_db_SAS2IDM_SSIS.sql
GO
USE [SAS2000_LIVE_SSMPD];
GO
:r C:\scripts\SAS2IDM.SSIS\Create-Role_db_SAS2IDM_SSIS.sql
GO
USE [SAS2000_LIVE_SSMPM];
GO
:r C:\scripts\SAS2IDM.SSIS\Create-Role_db_SAS2IDM_SSIS.sql
GO
USE [SAS2000_LIVE_SSMPT];
GO
:r C:\scripts\SAS2IDM.SSIS\Create-Role_db_SAS2IDM_SSIS.sql
GO
USE [SAS2000_LIVE_SSPCM];
GO
:r C:\scripts\SAS2IDM.SSIS\Create-Role_db_SAS2IDM_SSIS.sql
GO
USE [SAS2000_LIVE_SSPCT];
GO
:r C:\scripts\SAS2IDM.SSIS\Create-Role_db_SAS2IDM_SSIS.sql
GO
USE [SAS2000_LIVE_SSPGE];
GO
:r C:\scripts\SAS2IDM.SSIS\Create-Role_db_SAS2IDM_SSIS.sql
GO
USE [SAS2000_LIVE_SSPNN];
GO
:r C:\scripts\SAS2IDM.SSIS\Create-Role_db_SAS2IDM_SSIS.sql
GO
USE [SAS2000_LIVE_SSPPA];
GO
:r C:\scripts\SAS2IDM.SSIS\Create-Role_db_SAS2IDM_SSIS.sql
GO
USE [SAS2000_LIVE_SSRCP];
GO
:r C:\scripts\SAS2IDM.SSIS\Create-Role_db_SAS2IDM_SSIS.sql
GO
USE [SAS2000_LIVE_SSTPW];
GO
:r C:\scripts\SAS2IDM.SSIS\Create-Role_db_SAS2IDM_SSIS.sql
GO
