TRUNCATE TABLE "ChangeLog" CASCADE;
TRUNCATE TABLE "Changes" CASCADE;
TRUNCATE TABLE "Container" CASCADE;
TRUNCATE TABLE "Entity" CASCADE;
TRUNCATE TABLE "Origin" CASCADE;
TRUNCATE TABLE "StoredValueCollection" CASCADE;